### ISSUE TITLE
Heroku app is down! Please reupload it if you can......

### ISSUE THREAD

**Issue by csabagabor** [shalvah/cors-escape#2]

**Comment by shalvah** [comment]
I had to take it down because it violated Heroku's policies (they don't allow proxies). I'm no longer pursuing this project, so if you wish, you can try hosting it on another platform (now.sh and AWS Lambda are good examples and you can get them for free).

**Comment by csabagabor** [comment]
OK, thank you very much for the fast reply. I think I will fork your project and host is somewhere. And I am really sorry for the stupid title of this Issue(I realized only now.....).
